<script setup>
import { onMounted, ref } from 'vue';
import PageHeader from '../components/PageHeader.vue';
import StatusPanel from '../components/StatusPanel.vue';
import { api } from '../lib/api';

const slots = ref([]); const loading = ref(true); const error = ref(''); const notice = ref(''); const saving = ref(null);
async function load() { loading.value = true; error.value = ''; try { slots.value = await api('/admin/ads/billing-rates'); } catch (reason) { error.value = reason.message; } finally { loading.value = false; } }
async function saveRate(rate) { saving.value = `rate-${rate.id}`; error.value = ''; notice.value = ''; try { await api(`/admin/ads/billing-rates/${rate.id}`, { method: 'PUT', body: { rate: Number(rate.rate), minimum_charge: Number(rate.minimum_charge), currency: rate.currency, requires_prepayment: Boolean(rate.requires_prepayment), is_active: Boolean(rate.is_active) } }); notice.value = `${rate.billing_model} rate saved.`; } catch (reason) { error.value = reason.message; } finally { saving.value = null; } }
async function toggleSlot(slot) { saving.value = `slot-${slot.id}`; try { const updated = await api(`/admin/ads/placements/${slot.id}`, { method: 'PUT', body: { is_active: !slot.is_active } }); slot.is_active = updated.is_active; notice.value = `${slot.label} ${slot.is_active ? 'enabled' : 'disabled'}.`; } catch (reason) { error.value = reason.message; } finally { saving.value = null; } }
const unit = (model) => ({ CPM: '1,000 impressions', CPC: 'valid click', CPV: 'valid view', FLAT: 'day' }[model]);
onMounted(load);
</script>

<template><div class="admin-page"><PageHeader eyebrow="Advertising billing" title="Rates & placements" description="These rates drive public quotes and new campaign invoices."><RouterLink class="admin-secondary" to="/ads/billing">Billing dashboard</RouterLink></PageHeader><StatusPanel tone="success" :message="notice"/><StatusPanel tone="error" :message="error"/><div v-if="loading" class="admin-loading">Loading billing rates…</div><section v-else class="rate-slots"><article v-for="slot in slots" :key="slot.id" class="admin-panel"><header><div><p>{{ slot.media_type }} · {{ slot.code }}</p><h2>{{ slot.label }}</h2><span>{{ slot.description }}</span></div><button class="admin-secondary" :disabled="saving" @click="toggleSlot(slot)">{{ slot.is_active ? 'Enabled' : 'Disabled' }}</button></header><div class="rate-grid"><form v-for="rate in slot.rates" :key="rate.id" @submit.prevent="saveRate(rate)"><div class="rate-heading"><b>{{ rate.billing_model }}</b><span>per {{ unit(rate.billing_model) }}</span></div><label>Rate<input v-model="rate.rate" type="number" min="0" step="0.0001"></label><label>Minimum charge<input v-model="rate.minimum_charge" type="number" min="0" step="0.01"></label><label>Currency<input v-model.trim="rate.currency" maxlength="3"></label><label class="check"><input v-model="rate.requires_prepayment" type="checkbox"> Prepaid</label><label class="check"><input v-model="rate.is_active" type="checkbox"> Active</label><button class="admin-primary" :disabled="saving === `rate-${rate.id}`">{{ saving === `rate-${rate.id}` ? 'Saving…' : 'Save rate' }}</button></form></div></article></section></div></template>

<style scoped>.rate-slots{display:grid;gap:15px}.admin-panel>header span{display:block;margin-top:5px;color:var(--a-muted);font-size:11px}.rate-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;padding:16px}.rate-grid form{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:16px;border:1px solid var(--a-line);border-radius:13px;background:rgba(0,0,0,.1)}.rate-heading,.rate-grid form>button{grid-column:1/-1}.rate-heading{display:flex;align-items:end;justify-content:space-between}.rate-heading b{color:var(--a-cyan);font:800 21px 'Manrope',sans-serif}.rate-heading span{color:var(--a-muted);font-size:9px}.rate-grid label{display:grid;gap:6px;color:var(--a-muted);font-size:10px;font-weight:700}.rate-grid input:not([type=checkbox]){width:100%;min-height:40px;padding:0 9px;border:1px solid var(--a-line);border-radius:8px;background:rgba(4,12,15,.6);color:var(--a-text)}.rate-grid label.check{display:flex;align-items:center;gap:7px}.rate-grid label.check input{accent-color:var(--a-cyan)}@media(max-width:1000px){.rate-grid{grid-template-columns:1fr 1fr}}@media(max-width:650px){.rate-grid{grid-template-columns:1fr}}</style>
